name: android_battery_optimizations
description: You can check battery otimization status and launch permission dialog. This plugin does not cover "manufacturer battery optimizations" checks yet. Planning to add this feature soon.
version: 0.0.1
homepage: https://github.com/edex96/android_battery_optimizations

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.android_battery_optimizations
        pluginClass: AndroidBatteryOptimizationsPlugin
